version: '3'
services:
  securityservice:
    build:
        dockerfile: ./Dockerfile
        context: ./
    image: marcusbianchi/securityservice
    container_name: securityservice        
    volumes:
      - keysvolume:/var/keys/  
    ports:
        - "5010:5010"
volumes:
  keysvolume:
    driver: local
    driver_opts:
      type: none
      device: /var/keys/
      o: bind